services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - ./src:/app
    environment:
      - WATCHPACK_POLLING=true
      - MONGODB_URI=mongodb://db:27017/nextjs-app
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
